### ISSUE TITLE
Highlight arcs connected to places/transitions

### ISSUE THREAD

**Issue by pragathip** [AndrewJSchoen/Petri#1]
When hovering on a place or transition, it would be helpful to see the arcs (both input and output) highlighted to make it easier to follow the flow. It would also be helpful to have the labels of the connected places/transitions show up. I have attached an example for how it might look.

![hover-label](https://github.com/AndrewJSchoen/Petri/assets/1701436/4fed4d2e-bf6d-431f-97e1-63a6272ece21)

**Comment by AndrewJSchoen** [comment]
This has been added in the most recent version!
